project:
  type: website
  output-dir: docs
  render: 
    - 01-introduction.qmd
    - 02-tidyverse.qmd
    - 03-visualizations.qmd

website:
  title: "Intro to R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01-introduction.qmd
      - 02-tidyverse.qmd
      - 03-visualizations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged



